# Site settings
title: Amazfit Bip Font Creator
description: Font Creator for Amazfit Bip (*.ft)
cover: assets/images/amazfit_bip_smartwatch_kokoda_green_trench_coat.jpg
logo: assets/images/amazfit_bip_smartwatch_onyx_black_hero.png
favicon: assets/images/favicon.png
baseurl: "/amazfit-bip/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://jacegem.github.io" # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

# Social
# facebook: facebook
# twitter: twitter
github:  jacegem

#Additional Pages
# about: about
# contact: contact
# privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: jacegem #github username
repo: https://github.com/jacegem #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://github.com/jacegem/amazfit-bip
source_url:  https://github.com/jacegem/amazfit-bip #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml


remote_theme: hanuman